repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
    - id: black
      args: ['--check', '-l', '120', '-t', 'py38', '-t', 'py39', '-t', 'py310', '-t', 'py311']
